import { BodySystem } from "@/types/health";

export const bodySystems: BodySystem[] = [
  {
    id: "cardiovascular",
    name: "Cardiovascular System",
    shortLabel: "Cardiovascular",
    status: "stable",
    statusNote: "Stable",
    summary: "Lipids and heart metrics are within personal targets and improving.",
    color: "sys-cardiovascular",
    hasDetailPage: true,
  },
  {
    id: "gut",
    name: "Gut & Microbiome",
    shortLabel: "Gut",
    status: "needs_data",
    statusNote: "More data needed",
    summary: "Last stool panel was 4 months ago — a refresh would sharpen this view.",
    color: "sys-gut",
    hasDetailPage: true,
  },
  {
    id: "brain",
    name: "Brain & Mental Wellbeing",
    shortLabel: "Sleep / Brain",
    status: "improving",
    statusNote: "Improving",
    summary: "Mood and focus trending up, though sleep consistency still lags.",
    color: "sys-brain",
    hasDetailPage: true,
  },
  {
    id: "metabolic",
    name: "Metabolic Health",
    shortLabel: "Metabolic",
    status: "stable",
    statusNote: "Stable",
    summary: "Glucose and body composition holding steady near target.",
    color: "sys-metabolic",
    hasDetailPage: true,
  },
  {
    id: "musculoskeletal",
    name: "Musculoskeletal System",
    shortLabel: "Musculoskeletal",
    status: "good",
    statusNote: "Good",
    summary: "Strength trending up, minor left shoulder soreness from Judo.",
    color: "sys-musculoskeletal",
    hasDetailPage: true,
  },
  {
    id: "immune",
    name: "Immune System",
    shortLabel: "Immune",
    status: "stable",
    statusNote: "Stable",
    summary: "No recent illness. Resilience markers unremarkable.",
    color: "sys-immune",
    hasDetailPage: true,
  },
  {
    id: "lungs",
    name: "Respiratory System",
    shortLabel: "Lungs",
    status: "good",
    statusNote: "Good",
    summary: "VO2max improving alongside Zone 2 training volume.",
    color: "sys-lungs",
    hasDetailPage: false,
  },
  {
    id: "liver",
    name: "Liver",
    shortLabel: "Liver",
    status: "stable",
    statusNote: "Stable",
    summary: "Liver enzymes within lab reference range at last panel.",
    color: "sys-liver",
    hasDetailPage: true,
  },
  {
    id: "kidneys",
    name: "Kidneys",
    shortLabel: "Kidneys",
    status: "stable",
    statusNote: "Stable",
    summary: "eGFR and creatinine unremarkable at last panel.",
    color: "sys-kidneys",
    hasDetailPage: true,
  },
];

export function getBodySystem(id: string) {
  return bodySystems.find((s) => s.id === id);
}
