import { HealthEvent } from "@/types/health";

export const timelineEvents: HealthEvent[] = [
  {
    id: "evt-1",
    type: "lab",
    date: "2026-08-21",
    title: "Laboratory panel · Quest Diagnostics",
    detail: "Full lipid panel plus HbA1c and fasting glucose.",
    metrics: [
      { label: "ApoB", value: "74 mg/dL" },
      { label: "LDL-C", value: "101 mg/dL" },
      { label: "HbA1c", value: "5.2%" },
    ],
    tags: ["Labs"],
    source: { type: "lab", label: "Quest Diagnostics", date: "2026-08-21" },
  },
  {
    id: "evt-2",
    type: "journal",
    date: "2026-08-18",
    title: "Journal entry",
    detail: "“Very tired today after a poor night of sleep.”",
    tags: ["Journal", "Sleep"],
    source: { type: "journal", label: "Journal", subjective: true },
  },
  {
    id: "evt-3",
    type: "training",
    date: "2026-08-15",
    title: "Judo",
    detail: "90 min · High intensity",
    metrics: [{ label: "Duration", value: "90 min" }],
    tags: ["Training"],
    source: { type: "manual", label: "Manual entry" },
  },
  {
    id: "evt-4",
    type: "experiment",
    date: "2026-08-10",
    title: "Health experiment started",
    detail: "No large meals within 3 hours before bedtime.",
    tags: ["Experiments", "Nutrition"],
    source: { type: "manual", label: "Manual entry" },
  },
  {
    id: "evt-5",
    type: "weight",
    date: "2026-08-05",
    title: "Body composition scan",
    metrics: [
      { label: "Weight", value: "78.4 kg" },
      { label: "Body fat", value: "16.9%" },
    ],
    tags: ["Nutrition"],
    source: { type: "manual", label: "InBody scan", date: "2026-08-05" },
  },
  {
    id: "evt-6",
    type: "training",
    date: "2026-08-03",
    title: "Zone 2 run",
    detail: "50 min · HR avg 138 bpm",
    tags: ["Training"],
    source: { type: "wearable", label: "Amazfit Helio Strap" },
  },
  {
    id: "evt-7",
    type: "journal",
    date: "2026-07-29",
    title: "Journal entry",
    detail: "“Bloating after dinner again, third time this month.”",
    tags: ["Journal", "Symptoms"],
    source: { type: "journal", label: "Journal", subjective: true },
  },
  {
    id: "evt-8",
    type: "supplement",
    date: "2026-07-20",
    title: "Started magnesium glycinate",
    detail: "400mg before bed, aiming to support sleep quality.",
    tags: ["Nutrition"],
    source: { type: "manual", label: "Manual entry" },
  },
  {
    id: "evt-9",
    type: "wearable",
    date: "2026-07-12",
    title: "HRV baseline shift detected",
    detail: "30-day baseline rose from 49ms to 55ms.",
    tags: ["Sleep"],
    source: { type: "calculated", label: "Calculated from wearable data" },
  },
  {
    id: "evt-10",
    type: "illness",
    date: "2026-06-28",
    title: "Mild cold",
    detail: "3 days, reduced training load.",
    tags: ["Symptoms"],
    source: { type: "manual", label: "Manual entry" },
  },
  {
    id: "evt-11",
    type: "lab",
    date: "2026-05-04",
    title: "Stool test panel · Viome",
    metrics: [
      { label: "Diversity index", value: "6.1" },
      { label: "Calprotectin", value: "41 µg/g" },
    ],
    tags: ["Labs"],
    source: { type: "lab", label: "Viome", date: "2026-05-04" },
  },
  {
    id: "evt-12",
    type: "goal",
    date: "2026-04-15",
    title: "Goal set: Judo Competition",
    detail: "Target competition date 15 May 2027.",
    tags: ["Training"],
    source: { type: "manual", label: "Manual entry" },
  },
  {
    id: "evt-13",
    type: "lab",
    date: "2026-01-18",
    title: "Laboratory panel · Quest Diagnostics",
    metrics: [
      { label: "ApoB", value: "78 mg/dL" },
      { label: "LDL-C", value: "112 mg/dL" },
      { label: "HbA1c", value: "5.3%" },
    ],
    tags: ["Labs"],
    source: { type: "lab", label: "Quest Diagnostics", date: "2026-01-18" },
  },
];

export const timelineFilters = [
  "Labs",
  "Sleep",
  "Training",
  "Journal",
  "Nutrition",
  "Symptoms",
  "Experiments",
] as const;
