import type { BodySystem } from "@/lib/generated/prisma/client";

// The canonical catalog of biomarker *definitions* — lab values and
// wearable-style metrics alike, since a BiomarkerMeasurement only differs by
// its sourceType. This is what prisma/seed.ts loads, and what alias
// resolution (lib/services/biomarker.service.ts) matches extracted lab
// field names against.
export interface BiomarkerCatalogEntry {
  canonicalKey: string;
  displayName: string;
  shortName?: string;
  category: string;
  defaultUnit?: string;
  description?: string;
  whyItMatters?: string;
  bodySystem?: BodySystem;
  aliases: string[];
}

export const biomarkerCatalog: BiomarkerCatalogEntry[] = [
  {
    canonicalKey: "apob",
    displayName: "Apolipoprotein B",
    shortName: "ApoB",
    category: "Lipids",
    defaultUnit: "mg/dL",
    description:
      "ApoB counts the number of atherogenic (potentially artery-clogging) lipoprotein particles in your blood, including LDL.",
    whyItMatters:
      "Many longevity-focused clinicians consider ApoB a more direct measure of cardiovascular risk than LDL-C alone, since it reflects particle number rather than cholesterol mass.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Apo B", "ApoB", "Apolipoprotein-B", "Apolipoprotein B", "APOB"],
  },
  {
    canonicalKey: "ldl_c",
    displayName: "LDL Cholesterol",
    shortName: "LDL-C",
    category: "Lipids",
    defaultUnit: "mg/dL",
    description: "Low-density lipoprotein cholesterol, the cholesterol carried by ApoB particles.",
    whyItMatters: "Elevated LDL-C over time is associated with atherosclerotic plaque buildup. Trend matters more than any single reading.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["LDL-C", "LDL Cholesterol", "LDL", "Low-Density Lipoprotein"],
  },
  {
    canonicalKey: "hdl_c",
    displayName: "HDL Cholesterol",
    shortName: "HDL-C",
    category: "Lipids",
    defaultUnit: "mg/dL",
    description: "High-density lipoprotein cholesterol, involved in reverse cholesterol transport.",
    whyItMatters: "Higher HDL-C is generally associated with favorable cardiovascular outcomes.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["HDL-C", "HDL Cholesterol", "HDL", "High-Density Lipoprotein"],
  },
  {
    canonicalKey: "triglycerides",
    displayName: "Triglycerides",
    category: "Lipids",
    defaultUnit: "mg/dL",
    description: "A type of fat in the blood, sensitive to diet, alcohol, and metabolic health.",
    whyItMatters: "Elevated triglycerides often track with insulin resistance and late, large meals.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Triglycerides", "TG", "Trigs"],
  },
  {
    canonicalKey: "total_cholesterol",
    displayName: "Total Cholesterol",
    category: "Lipids",
    defaultUnit: "mg/dL",
    description: "The sum of all cholesterol carried in the blood, across all lipoprotein types.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Total Cholesterol", "Cholesterol, Total", "TC"],
  },
  {
    canonicalKey: "lp_a",
    displayName: "Lipoprotein(a)",
    shortName: "Lp(a)",
    category: "Lipids",
    defaultUnit: "nmol/L",
    description: "A genetically-determined lipoprotein particle associated with cardiovascular risk.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Lp(a)", "Lipoprotein (a)", "Lipoprotein a", "LPA"],
  },
  {
    canonicalKey: "resting_hr",
    displayName: "Resting Heart Rate",
    shortName: "Resting HR",
    category: "Cardiac function",
    defaultUnit: "bpm",
    description: "Heart rate while fully at rest, typically measured overnight.",
    whyItMatters: "A lower resting heart rate generally reflects improving aerobic fitness.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Resting HR", "Resting Heart Rate", "RHR"],
  },
  {
    canonicalKey: "hrv",
    displayName: "Heart Rate Variability",
    shortName: "HRV",
    category: "Cardiac function",
    defaultUnit: "ms",
    description: "Variation in time between heartbeats, a proxy for autonomic nervous system balance.",
    whyItMatters: "Higher HRV generally indicates better recovery capacity; dips often follow poor sleep, stress, or heavy training.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["HRV", "Heart Rate Variability"],
  },
  {
    canonicalKey: "vo2max",
    displayName: "VO2 Max",
    shortName: "VO2max",
    category: "Cardiac function",
    defaultUnit: "mL/kg/min",
    description: "Estimated maximum rate of oxygen consumption during exercise, a strong longevity marker.",
    whyItMatters: "VO2max is one of the metrics most consistently linked to all-cause mortality risk in longevity research.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["VO2max", "VO2 Max", "VO2-Max"],
  },
  {
    canonicalKey: "blood_pressure_systolic",
    displayName: "Blood Pressure (Systolic)",
    shortName: "Systolic BP",
    category: "Cardiac function",
    defaultUnit: "mmHg",
    description: "Pressure in the arteries when the heart beats.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Systolic", "Systolic BP", "Blood Pressure Systolic", "SYS"],
  },
  {
    canonicalKey: "blood_pressure_diastolic",
    displayName: "Blood Pressure (Diastolic)",
    shortName: "Diastolic BP",
    category: "Cardiac function",
    defaultUnit: "mmHg",
    description: "Pressure in the arteries when the heart rests between beats.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Diastolic", "Diastolic BP", "Blood Pressure Diastolic", "DIA"],
  },
  {
    canonicalKey: "hba1c",
    displayName: "Hemoglobin A1c",
    shortName: "HbA1c",
    category: "Glycemic",
    defaultUnit: "%",
    description: "Reflects average blood glucose levels over the preceding ~3 months.",
    whyItMatters: "A core marker of long-term glycemic control and metabolic health.",
    bodySystem: "METABOLIC",
    aliases: ["HbA1c", "Hemoglobin A1c", "A1C", "Hgb A1c"],
  },
  {
    canonicalKey: "fasting_glucose",
    displayName: "Fasting Glucose",
    category: "Glycemic",
    defaultUnit: "mg/dL",
    description: "Blood glucose measured after an overnight fast.",
    bodySystem: "METABOLIC",
    aliases: ["Fasting Glucose", "Glucose, Fasting", "FBG"],
  },
  {
    canonicalKey: "body_fat_percentage",
    displayName: "Body Fat Percentage",
    shortName: "Body Fat %",
    category: "Body composition",
    defaultUnit: "%",
    description: "Estimated proportion of total body mass that is fat tissue.",
    bodySystem: "METABOLIC",
    aliases: ["Body Fat %", "Body Fat Percentage", "% Body Fat"],
  },
  {
    canonicalKey: "hs_crp",
    displayName: "High-Sensitivity C-Reactive Protein",
    shortName: "hs-CRP",
    category: "Inflammation",
    defaultUnit: "mg/L",
    description: "A sensitive marker of systemic inflammation.",
    bodySystem: "IMMUNE",
    aliases: ["hs-CRP", "hsCRP", "CRP", "C-Reactive Protein"],
  },
  {
    canonicalKey: "ferritin",
    displayName: "Ferritin",
    category: "Hematology",
    defaultUnit: "ng/mL",
    description: "Reflects the body's iron stores.",
    bodySystem: "METABOLIC",
    aliases: ["Ferritin"],
  },
  {
    canonicalKey: "vitamin_d",
    displayName: "Vitamin D (25-OH)",
    shortName: "Vitamin D",
    category: "Micronutrients",
    defaultUnit: "ng/mL",
    description: "25-hydroxyvitamin D, the standard measure of vitamin D status.",
    bodySystem: "IMMUNE",
    aliases: ["Vitamin D", "25-OH Vitamin D", "Vitamin D3", "25-Hydroxyvitamin D"],
  },
  {
    canonicalKey: "tsh",
    displayName: "Thyroid Stimulating Hormone",
    shortName: "TSH",
    category: "Hormones",
    defaultUnit: "uIU/mL",
    description: "Regulates thyroid hormone production; a core thyroid function screen.",
    bodySystem: "METABOLIC",
    aliases: ["TSH", "Thyroid Stimulating Hormone", "Thyrotropin"],
  },
  {
    canonicalKey: "testosterone",
    displayName: "Testosterone (Total)",
    shortName: "Testosterone",
    category: "Hormones",
    defaultUnit: "ng/dL",
    description: "Total circulating testosterone.",
    bodySystem: "METABOLIC",
    aliases: ["Testosterone", "Total Testosterone", "Testosteron", "Gesamttestosteron", "Тестостерон", "Общий тестостерон"],
  },
  {
    canonicalKey: "free_testosterone",
    displayName: "Free Testosterone",
    shortName: "Free T",
    category: "Hormones",
    defaultUnit: "pg/mL",
    description: "The unbound, biologically active fraction of testosterone.",
    bodySystem: "METABOLIC",
    aliases: ["Free Testosterone", "Freies Testosteron", "Свободный тестостерон"],
  },
  {
    canonicalKey: "estradiol",
    displayName: "Estradiol",
    shortName: "E2",
    category: "Hormones",
    defaultUnit: "pg/mL",
    description: "The primary estrogen; relevant to both female and male hormone panels.",
    bodySystem: "METABOLIC",
    aliases: ["Estradiol", "E2", "Östradiol", "Oestradiol", "Эстрадиол"],
  },
  {
    canonicalKey: "shbg",
    displayName: "Sex Hormone Binding Globulin",
    shortName: "SHBG",
    category: "Hormones",
    defaultUnit: "nmol/L",
    description: "Binds sex hormones in the blood; affects how much testosterone/estradiol is free versus bound.",
    bodySystem: "METABOLIC",
    aliases: ["SHBG", "Sex Hormone Binding Globulin", "Sexualhormon-bindendes Globulin", "ГСПГ"],
  },
  {
    canonicalKey: "lh",
    displayName: "Luteinizing Hormone",
    shortName: "LH",
    category: "Hormones",
    defaultUnit: "mIU/mL",
    description: "A pituitary hormone that signals the gonads; part of a standard hormone-axis panel.",
    bodySystem: "METABOLIC",
    aliases: ["LH", "Luteinizing Hormone", "Luteinisierendes Hormon", "ЛГ", "Лютеинизирующий гормон"],
  },
  {
    canonicalKey: "fsh",
    displayName: "Follicle Stimulating Hormone",
    shortName: "FSH",
    category: "Hormones",
    defaultUnit: "mIU/mL",
    description: "A pituitary hormone involved in reproductive function; commonly measured alongside LH.",
    bodySystem: "METABOLIC",
    aliases: ["FSH", "Follicle Stimulating Hormone", "Follikelstimulierendes Hormon", "ФСГ", "Фолликулостимулирующий гормон"],
  },
  {
    canonicalKey: "prolactin",
    displayName: "Prolactin",
    category: "Hormones",
    defaultUnit: "ng/mL",
    description: "A pituitary hormone; commonly included in a broader hormone panel.",
    bodySystem: "METABOLIC",
    aliases: ["Prolactin", "Prolaktin", "Пролактин"],
  },
  {
    canonicalKey: "dhea_s",
    displayName: "DHEA-Sulfate",
    shortName: "DHEA-S",
    category: "Hormones",
    defaultUnit: "ug/dL",
    description: "An adrenal hormone precursor, commonly measured alongside testosterone.",
    bodySystem: "METABOLIC",
    aliases: ["DHEA-S", "DHEA Sulfate", "DHEAS", "ДГЭА-С", "ДГЭА-сульфат"],
  },
  {
    canonicalKey: "cortisol",
    displayName: "Cortisol",
    category: "Hormones",
    defaultUnit: "ug/dL",
    description: "The primary stress hormone; commonly measured as a morning (fasting) sample given its daily rhythm.",
    bodySystem: "METABOLIC",
    aliases: ["Cortisol", "Kortisol", "Кортизол"],
  },
  {
    canonicalKey: "free_t3",
    displayName: "Free T3",
    shortName: "fT3",
    category: "Hormones",
    defaultUnit: "pg/mL",
    description: "The active, unbound form of triiodothyronine; part of a thyroid panel alongside TSH and fT4.",
    bodySystem: "METABOLIC",
    aliases: ["Free T3", "fT3", "FT3", "Freies T3", "Свободный Т3"],
  },
  {
    canonicalKey: "free_t4",
    displayName: "Free T4",
    shortName: "fT4",
    category: "Hormones",
    defaultUnit: "ng/dL",
    description: "The active, unbound form of thyroxine; part of a thyroid panel alongside TSH and fT3.",
    bodySystem: "METABOLIC",
    aliases: ["Free T4", "fT4", "FT4", "Freies T4", "Свободный Т4"],
  },
  {
    canonicalKey: "homocysteine",
    displayName: "Homocysteine",
    category: "Cardiac function",
    defaultUnit: "umol/L",
    description: "An amino acid; elevated levels have been associated with cardiovascular risk.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Homocysteine", "HCY"],
  },
  {
    canonicalKey: "alt",
    displayName: "Alanine Aminotransferase",
    shortName: "ALT",
    category: "Liver function",
    defaultUnit: "U/L",
    description: "A liver enzyme; elevated levels can indicate liver stress or damage.",
    bodySystem: "LIVER",
    aliases: ["ALT", "Alanine Aminotransferase", "SGPT"],
  },
  {
    canonicalKey: "ast",
    displayName: "Aspartate Aminotransferase",
    shortName: "AST",
    category: "Liver function",
    defaultUnit: "U/L",
    description: "A liver enzyme also found in muscle; used alongside ALT to assess liver health.",
    bodySystem: "LIVER",
    aliases: ["AST", "Aspartate Aminotransferase", "SGOT"],
  },
  {
    canonicalKey: "creatinine",
    displayName: "Creatinine",
    category: "Kidney function",
    defaultUnit: "mg/dL",
    description: "A waste product filtered by the kidneys; a core marker of kidney function.",
    bodySystem: "KIDNEYS",
    aliases: ["Creatinine"],
  },
  {
    canonicalKey: "egfr",
    displayName: "Estimated Glomerular Filtration Rate",
    shortName: "eGFR",
    category: "Kidney function",
    defaultUnit: "mL/min",
    description: "An estimate of how well the kidneys filter blood.",
    bodySystem: "KIDNEYS",
    aliases: ["eGFR", "GFR", "Estimated GFR"],
  },
  {
    canonicalKey: "microbiome_diversity",
    displayName: "Microbiome Diversity Index",
    shortName: "Diversity Index",
    category: "Gut/Microbiome",
    defaultUnit: "score",
    description: "A composite score of bacterial species richness and evenness in the gut.",
    whyItMatters: "Greater diversity is broadly associated with digestive and metabolic resilience.",
    bodySystem: "GUT",
    aliases: ["Diversity Index", "Microbiome Diversity", "Shannon Diversity Index"],
  },
  {
    canonicalKey: "calprotectin",
    displayName: "Fecal Calprotectin",
    shortName: "Calprotectin",
    category: "Gut/Microbiome",
    defaultUnit: "ug/g",
    description: "A marker of intestinal inflammation, released by white blood cells in the gut lining.",
    whyItMatters: "Persistently elevated levels can indicate inflammatory gut activity worth discussing with a clinician.",
    bodySystem: "GUT",
    aliases: ["Calprotectin", "Fecal Calprotectin"],
  },
  {
    canonicalKey: "pancreatic_elastase",
    displayName: "Pancreatic Elastase-1",
    shortName: "Elastase-1",
    category: "Gut/Microbiome",
    defaultUnit: "ug/g",
    description: "Reflects exocrine pancreatic function and digestive enzyme output.",
    whyItMatters: "Low levels can point toward poor fat digestion and nutrient absorption.",
    bodySystem: "GUT",
    aliases: ["Pancreatic Elastase-1", "Elastase-1", "Pancreatic Elastase"],
  },
  {
    canonicalKey: "sleep_duration",
    displayName: "Sleep Duration",
    category: "Sleep",
    defaultUnit: "hrs",
    description: "Total time asleep, as measured by a wearable.",
    bodySystem: "BRAIN",
    aliases: ["Sleep Duration", "Total Sleep Time"],
  },
  {
    canonicalKey: "sleep_score",
    displayName: "Sleep Score",
    category: "Sleep",
    defaultUnit: "/100",
    description: "A composite wearable score summarizing overall sleep quality.",
    bodySystem: "BRAIN",
    aliases: ["Sleep Score"],
  },
  {
    canonicalKey: "deep_sleep",
    displayName: "Deep Sleep",
    category: "Sleep",
    defaultUnit: "min",
    description: "Minutes spent in deep (slow-wave) sleep.",
    bodySystem: "BRAIN",
    aliases: ["Deep Sleep"],
  },
  {
    canonicalKey: "rem_sleep",
    displayName: "REM Sleep",
    category: "Sleep",
    defaultUnit: "min",
    description: "Minutes spent in REM sleep.",
    bodySystem: "BRAIN",
    aliases: ["REM Sleep"],
  },
  {
    canonicalKey: "stress_level",
    displayName: "Stress Level",
    category: "Sleep",
    defaultUnit: "/100",
    description: "A wearable-derived stress score based on heart rate patterns.",
    bodySystem: "BRAIN",
    aliases: ["Stress Level", "Stress Score"],
  },
  {
    canonicalKey: "training_load",
    displayName: "Training Load",
    category: "Training",
    defaultUnit: "AU",
    description: "A composite measure of cumulative training stress.",
    bodySystem: "MUSCULOSKELETAL",
    aliases: ["Training Load"],
  },
  {
    canonicalKey: "spo2",
    displayName: "Blood Oxygen Saturation",
    shortName: "SpO2",
    category: "Respiratory",
    defaultUnit: "%",
    description: "The percentage of oxygen-saturated hemoglobin in the blood.",
    bodySystem: "LUNGS",
    aliases: ["SpO2", "Blood Oxygen", "Oxygen Saturation"],
  },
  // --- Phase 5: additional wearable metric catalog entries ---------------
  // Added so the wearable importer has a canonical BiomarkerDefinition to
  // write against for every metric in its supported catalog (see
  // docs/WEARABLE_ARCHITECTURE.md, "Canonical metrics") — not derived from
  // any single device's proprietary formula.
  {
    canonicalKey: "light_sleep",
    displayName: "Light Sleep",
    category: "Sleep",
    defaultUnit: "min",
    description: "Minutes spent in light sleep.",
    bodySystem: "BRAIN",
    aliases: ["Light Sleep"],
  },
  {
    canonicalKey: "awake_duration",
    displayName: "Awake During Sleep",
    category: "Sleep",
    defaultUnit: "min",
    description: "Minutes spent awake within a sleep session.",
    bodySystem: "BRAIN",
    aliases: ["Awake Duration", "Time Awake"],
  },
  {
    canonicalKey: "sleep_efficiency",
    displayName: "Sleep Efficiency",
    category: "Sleep",
    defaultUnit: "%",
    description: "The percentage of time in bed actually spent asleep.",
    bodySystem: "BRAIN",
    aliases: ["Sleep Efficiency"],
  },
  {
    canonicalKey: "sleep_latency",
    displayName: "Sleep Latency",
    category: "Sleep",
    defaultUnit: "min",
    description: "Time taken to fall asleep after going to bed.",
    bodySystem: "BRAIN",
    aliases: ["Sleep Latency", "Time to Fall Asleep"],
  },
  {
    canonicalKey: "average_sleeping_heart_rate",
    displayName: "Average Sleeping Heart Rate",
    shortName: "Sleeping HR",
    category: "Cardiac function",
    defaultUnit: "bpm",
    description: "Average heart rate during sleep, distinct from the single lowest resting-HR reading.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Average Sleeping Heart Rate", "Sleeping HR"],
  },
  {
    canonicalKey: "heart_rate",
    displayName: "Average Heart Rate",
    shortName: "Avg HR",
    category: "Cardiac function",
    defaultUnit: "bpm",
    description: "Average all-day heart rate, distinct from resting heart rate.",
    bodySystem: "CARDIOVASCULAR",
    aliases: ["Heart Rate", "Average Heart Rate"],
  },
  {
    canonicalKey: "respiratory_rate",
    displayName: "Respiratory Rate",
    category: "Respiratory",
    defaultUnit: "breaths/min",
    description: "Average breaths per minute, typically measured overnight.",
    bodySystem: "LUNGS",
    aliases: ["Respiratory Rate", "Breathing Rate"],
  },
  {
    canonicalKey: "steps",
    displayName: "Steps",
    category: "Activity",
    defaultUnit: "steps",
    description: "Daily step count.",
    bodySystem: "METABOLIC",
    aliases: ["Steps", "Step Count"],
  },
  {
    canonicalKey: "active_minutes",
    displayName: "Active Minutes",
    category: "Activity",
    defaultUnit: "min",
    description: "Minutes of recorded physical activity in a day.",
    bodySystem: "METABOLIC",
    aliases: ["Active Minutes"],
  },
  {
    canonicalKey: "distance",
    displayName: "Distance",
    category: "Activity",
    defaultUnit: "km",
    description: "Daily distance covered.",
    bodySystem: "METABOLIC",
    aliases: ["Distance"],
  },
  {
    canonicalKey: "calories_active",
    displayName: "Active Calories",
    category: "Activity",
    defaultUnit: "kcal",
    description: "Calories burned from recorded activity, excluding basal metabolic rate.",
    bodySystem: "METABOLIC",
    aliases: ["Active Calories", "Calories Active"],
  },
  {
    canonicalKey: "ggt",
    displayName: "Gamma-Glutamyl Transferase",
    shortName: "GGT",
    category: "Liver function",
    defaultUnit: "U/L",
    description: "An enzyme associated with the liver's bile ducts (the hepatobiliary system).",
    whyItMatters:
      "GGT rises with hepatobiliary stress or certain medications/alcohol intake. It's most informative alongside ALT and AST, not in isolation.",
    bodySystem: "LIVER",
    aliases: ["GGT", "Gamma-Glutamyl Transferase", "Gamma GT"],
  },
  {
    canonicalKey: "bilirubin_total",
    displayName: "Total Bilirubin",
    shortName: "Bilirubin",
    category: "Liver function",
    defaultUnit: "mg/dL",
    description: "A byproduct of red blood cell breakdown, processed by the liver and excreted in bile.",
    whyItMatters: "Reflects both red blood cell turnover and how well the liver is processing and excreting that byproduct.",
    bodySystem: "LIVER",
    aliases: ["Total Bilirubin", "Bilirubin, Total", "Bilirubin"],
  },
  // --- Blood / immune differential (CBC-style) ---
  {
    canonicalKey: "erythrocytes",
    displayName: "Red Blood Cell Count",
    shortName: "RBC",
    category: "Hematology",
    defaultUnit: "M/uL",
    description: "The number of oxygen-carrying red blood cells (erythrocytes) per microliter of blood.",
    bodySystem: "IMMUNE",
    aliases: ["RBC", "Red Blood Cell Count", "Erythrocytes"],
  },
  {
    canonicalKey: "hemoglobin",
    displayName: "Hemoglobin",
    shortName: "Hgb",
    category: "Hematology",
    defaultUnit: "g/dL",
    description: "The oxygen-carrying protein inside red blood cells.",
    bodySystem: "IMMUNE",
    aliases: ["Hemoglobin", "Hgb", "Haemoglobin"],
  },
  {
    canonicalKey: "hematocrit",
    displayName: "Hematocrit",
    shortName: "Hct",
    category: "Hematology",
    defaultUnit: "%",
    description: "The proportion of blood volume occupied by red blood cells.",
    bodySystem: "IMMUNE",
    aliases: ["Hematocrit", "Hct", "Haematocrit"],
  },
  {
    canonicalKey: "leukocytes",
    displayName: "White Blood Cell Count",
    shortName: "WBC",
    category: "Immune / Hematology",
    defaultUnit: "K/uL",
    description: "The total number of white blood cells (leukocytes), the immune system's circulating defense cells.",
    bodySystem: "IMMUNE",
    aliases: ["WBC", "White Blood Cell Count", "Leukocytes"],
  },
  {
    canonicalKey: "neutrophils",
    displayName: "Neutrophils",
    category: "Immune / Hematology",
    defaultUnit: "%",
    description: "The most abundant white blood cell type, first responders against bacterial infection.",
    bodySystem: "IMMUNE",
    aliases: ["Neutrophils", "Neutrophil %", "Neut"],
  },
  {
    canonicalKey: "lymphocytes",
    displayName: "Lymphocytes",
    category: "Immune / Hematology",
    defaultUnit: "%",
    description: "White blood cells (including T cells, B cells, NK cells) central to adaptive immunity.",
    bodySystem: "IMMUNE",
    aliases: ["Lymphocytes", "Lymphocyte %", "Lymph"],
  },
  {
    canonicalKey: "monocytes",
    displayName: "Monocytes",
    category: "Immune / Hematology",
    defaultUnit: "%",
    description: "White blood cells that mature into macrophages and dendritic cells, involved in longer-term immune response.",
    bodySystem: "IMMUNE",
    aliases: ["Monocytes", "Monocyte %", "Mono"],
  },
  {
    canonicalKey: "eosinophils",
    displayName: "Eosinophils",
    category: "Immune / Hematology",
    defaultUnit: "%",
    description: "White blood cells associated with allergic responses and parasitic infection defense.",
    bodySystem: "IMMUNE",
    aliases: ["Eosinophils", "Eosinophil %", "Eos"],
  },
  {
    canonicalKey: "basophils",
    displayName: "Basophils",
    category: "Immune / Hematology",
    defaultUnit: "%",
    description: "The least common white blood cell type, involved in inflammatory and allergic responses.",
    bodySystem: "IMMUNE",
    aliases: ["Basophils", "Basophil %", "Baso"],
  },
  {
    canonicalKey: "platelets",
    displayName: "Platelets",
    shortName: "PLT",
    category: "Hematology",
    defaultUnit: "K/uL",
    description: "Small cell fragments responsible for blood clotting.",
    bodySystem: "IMMUNE",
    aliases: ["Platelets", "PLT", "Platelet Count"],
  },
];
